export class LensoStock {
  constructor(
    // public StockDTLKey: number,
    public ItemCode: string,
    // public ItemDescription: string,
    // public UOM: string,
    // public Location: string,
    // public BatchNo: string,
    // public ProjNo: string,
    // public DeptNo: string,
    // public DocDate: Date,
    // public Seq: number,
    // public DocType: string,
    // public DocKey: number,
    // public DtlKey: number,
    public Qty: number,
    public Cost: number,
    // public AdjustedCost: number,
    // public TotalCost: number,
    // public CostType: string,
    // public LastModified: Date,
    // public ReferTo: string,
    // public InputCost: number,
    // public DocInfo: string,
    // public Seq2: number,
    // public CFTotalQty: number,
    // public CFTotalCost: number,
    // public CreatedTimeStamp: Date,
    // public AdjustedDate: Date,
    // public StockTransQueueKey: number,
    // public ReportingCost: number,
    // public ReportingTotalCost: number,
    // public FIFOCost: number,
    // public ReportingFIFOCost: number,
    // public BalanceFIFO: number,
    // public ReportingBalanceFIFO: number,
    // public CFTotalAdjustedCost: number
  ) { }
}