export class LensoItem {
  constructor(
    public AutoKey: number,
    public ItemCode: string,
    public DocKey: number,
    public Description: string,
    public Desc2: string,
    public FurtherDescription: string,
    public ItemGroup: string,
    public ItemType: string,
    public AssemblyCost: number,
    public LeadTime: number,
    public StockControl: boolean,
    public HasSerialNo: boolean,
    public HasBatchNo: boolean,
    public DutyRate: number,
    public TaxCode: string,
    public Note: string,
    public Image: {
      type: string;
      data: number[];
    },
    public CostingMethod: string,
    public SalesUOM: string,
    public PurchaseUOM: string,
    public ReportUOM: string,
    public LastModified: Date,
    public LastModifiedUserID: string,
    public CreatedTimeStamp: Date,
    public CreatedUserID: string,
    public IsActive: boolean,
    public LastUpdate: Date,
    public SNFormatName: string,
    public IsCalcBonusPoint: boolean,
    public MarkupRatio: number,
    public HasPromoter: boolean,
    public GlobalCode: string,
    public ItemBrand: string,
    public ItemClass: string,
    public ItemCategory: string,
    public LeadTimeDay: number,
    public ExternalLink: string,
    public Discontinued: boolean,
    public AutoUOMConversion: boolean,
    public BaseUOM: string,
    public BackOrderControl: boolean,
    public PurchaseTaxCode: string,
    public TariffCode: string,
    public Guid: string,
    public IsSalesItem: boolean,
    public IsPurchaseItem: boolean,
    public IsPOSItem: boolean,
    public IsRawMaterialItem: boolean,
    public IsFinishGoodsItem: boolean,
    public MainSupplier: string,
    public Classification: string,
    public MustGenerateEInvoice: boolean,
    public ImageFileName: string,
    public StockQty: number,
    public Cost: number,
    public Price: number,
    public Weight: number,
    public imageLoaded: boolean = false,
    public imageExist: boolean = false
  ) { }
}


